export const PREDICTION_MARKET_ABI = [
  { type: "function", name: "buyShares",     inputs: [{ name: "outcomeIndex", type: "uint256" }, { name: "usdcAmount", type: "uint256" }], outputs: [{ name: "sharesMinted", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "sellShares",    inputs: [{ name: "outcomeIndex", type: "uint256" }, { name: "sharesToSell", type: "uint256" }], outputs: [{ name: "usdcReturned", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "claimWinnings", inputs: [], outputs: [{ name: "payout", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "refundPosition",inputs: [], outputs: [{ name: "amount", type: "uint256" }], stateMutability: "nonpayable" },
  { type: "function", name: "settleMkt",     inputs: [], outputs: [], stateMutability: "nonpayable" },
  { type: "function", name: "outcomes",      inputs: [{ name: "index", type: "uint256" }], outputs: [{ name: "label", type: "string" }, { name: "totalShares", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "positions",     inputs: [{ name: "", type: "address" }, { name: "", type: "uint256" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "totalCollateral",   inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "openInterest",      inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "outcomeCount",      inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "tradingCloseTime",  inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "kickoffTime",       inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "settled",           inputs: [], outputs: [{ name: "", type: "bool" }],    stateMutability: "view" },
  { type: "function", name: "cancelled",         inputs: [], outputs: [{ name: "", type: "bool" }],    stateMutability: "view" },
  { type: "function", name: "disputed",          inputs: [], outputs: [{ name: "", type: "bool" }],    stateMutability: "view" },
  { type: "function", name: "paused",            inputs: [], outputs: [{ name: "", type: "bool" }],    stateMutability: "view" },
  { type: "function", name: "winningOutcomeIndex", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "oraclePostedAt",    inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "tradingFeeBps",     inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "cumulativeDeposits", inputs: [{ name: "", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "event", name: "SharesBought",    inputs: [{ name: "user", type: "address", indexed: true }, { name: "outcomeIndex", type: "uint256" }, { name: "shares", type: "uint256" }, { name: "usdcPaid", type: "uint256" }], anonymous: false },
  { type: "event", name: "SharesSold",      inputs: [{ name: "user", type: "address", indexed: true }, { name: "outcomeIndex", type: "uint256" }, { name: "shares", type: "uint256" }, { name: "usdcReturned", type: "uint256" }], anonymous: false },
  { type: "event", name: "WinningsClaimed", inputs: [{ name: "user", type: "address", indexed: true }, { name: "payout", type: "uint256" }], anonymous: false },
  { type: "event", name: "MarketSettled",   inputs: [{ name: "winningIndex", type: "uint256" }, { name: "settledAt", type: "uint256" }], anonymous: false },
  { type: "error", name: "TradingClosed",         inputs: [] },
  { type: "error", name: "ZeroAmount",            inputs: [] },
  { type: "error", name: "InsufficientShares",    inputs: [] },
  { type: "error", name: "MarketAlreadySettled",  inputs: [] },
  { type: "error", name: "MarketNotSettled",      inputs: [] },
  { type: "error", name: "MarketAlreadyCancelled",inputs: [] },
  { type: "error", name: "BlockedUser",           inputs: [] },
  { type: "error", name: "PositionLimitExceeded", inputs: [] },
] as const;

export const ERC20_ABI = [
  { type: "function", name: "approve",     inputs: [{ name: "spender", type: "address" }, { name: "amount", type: "uint256" }], outputs: [{ name: "", type: "bool" }], stateMutability: "nonpayable" },
  { type: "function", name: "allowance",   inputs: [{ name: "owner", type: "address" }, { name: "spender", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "balanceOf",   inputs: [{ name: "account", type: "address" }], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "decimals",    inputs: [], outputs: [{ name: "", type: "uint8" }], stateMutability: "view" },
] as const;

export const MARKET_FACTORY_ABI = [
  { type: "function", name: "createMarket",    inputs: [{ name: "fixtureId", type: "bytes32" }, { name: "question", type: "string" }, { name: "outcomeLabels", type: "string[]" }, { name: "kickoffTime", type: "uint256" }, { name: "tradingCloseOffset", type: "uint256" }, { name: "disputeWindowSecs", type: "uint256" }, { name: "settlementRuleHash", type: "bytes32" }], outputs: [{ name: "market", type: "address" }], stateMutability: "nonpayable" },
  { type: "function", name: "deployAndBuy",    inputs: [{ name: "fixtureId", type: "bytes32" }, { name: "outcomeIndex", type: "uint256" }, { name: "usdcAmount", type: "uint256" }], outputs: [{ name: "market", type: "address" }], stateMutability: "nonpayable" },
  { type: "function", name: "getFixture",      inputs: [{ name: "fixtureId", type: "bytes32" }], outputs: [{ name: "question", type: "string" }, { name: "outcomeLabels", type: "string[]" }, { name: "kickoffTime", type: "uint256" }, { name: "tradingCloseOffset", type: "uint256" }, { name: "disputeWindowSecs", type: "uint256" }, { name: "settlementRuleHash", type: "bytes32" }, { name: "registered", type: "bool" }], stateMutability: "view" },
  { type: "function", name: "marketsByFixture", inputs: [{ name: "fixtureId", type: "bytes32" }], outputs: [{ name: "market", type: "address" }], stateMutability: "view" },
  { type: "function", name: "allMarketsLength", inputs: [], outputs: [{ name: "", type: "uint256" }], stateMutability: "view" },
  { type: "function", name: "allMarkets",       inputs: [{ name: "", type: "uint256" }], outputs: [{ name: "", type: "address" }], stateMutability: "view" },
  { type: "event",    name: "MarketCreated",    inputs: [{ name: "market", type: "address", indexed: true }, { name: "fixtureId", type: "bytes32", indexed: true }, { name: "question", type: "string" }, { name: "outcomeLabels", type: "string[]" }, { name: "kickoffTime", type: "uint256" }], anonymous: false },
  { type: "error",    name: "MarketAlreadyExists",  inputs: [] },
  { type: "error",    name: "FixtureNotRegistered", inputs: [] },
  { type: "error",    name: "TradingClosed",        inputs: [] },
  { type: "error",    name: "InvalidOutcomeIndex",  inputs: [] },
] as const;
